spring:
  application:
    name: HRAirline
  datasource:
    url: jdbc:postgresql://localhost:5432/hrairline_db
    username: user1
    password: password1
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  sql:
    init:
      mode: always
      platform: postgres
  mail:
    host: mail.i2gether.com
    port: 475
    username: habibur@i2gether.com
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
server:
  port: 8082

app:
  jwt:
    # Fallback key used only for local development; always override in production
    secret-key: ${JWT_SECRET:474bd3d5f84b191febd7dfe467831f7801ce7f0e0403723225917a6764bb190f}
    expiration-ms: 86400000 # 24 hours in milliseconds